config/routes.rb
Rails.application.routes.draw do
  resources :scripts do
    get :pdf_download, on: :member
  end

  root 'scripts#index'

end

app/models/script.rb
class Script < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy, :pdf_download]

  # GET /scripts
  # GET /scripts.json
  def index
    @scripts = Script.all
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pdf_download
    render pdf: "#{@script.id}.pdf"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:body, :fountain_body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FountainApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scripts/_form.html.erb
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% @script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 20, cols: 100 %>

    <%= f.hidden_field :fountain_body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>Editing Script</h1>

<%= render 'form' %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %> |
<%= link_to 'Download pdf', pdf_download_script_path(@script) %>

app/views/scripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scripts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scripts.each do |script| %>
      <tr>
        <td><%= script.id %></td>
        <td><%= link_to 'Show', script %></td>
        <td><%= link_to 'Edit', edit_script_path(script) %></td>
        <td><%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Download pdf', pdf_download_script_path(script) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Script', new_script_path %>

app/views/scripts/new.html.erb
<h1>New Script</h1>

<%= render 'form' %>

<%= link_to 'Back', scripts_path %>

app/views/scripts/pdf_download.html.erb
<%= @script.fountain_body.html_safe %>

app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<p class='script_body'>
  <%= @script.fountain_body.html_safe %>
</p>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>